name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  check-commit-message:
    name: Check commit message should release
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check_message.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Check commit message
        id: check_message
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            return /chore:\s*release\s*v\d+\.\d+\.\d+/.test(context.payload.head_commit.message);

  release-android:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    needs: check-commit-message
    if: ${{ needs.check-commit-message.outputs.should_release == 'true' }}
    env:
      APK_FILE_PATH: ${{ github.workspace }}/src-tauri/gen/android/app/build/outputs/apk/universal/release
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@v4
        name: Setup pnpm
        with:
          version: 9
          run_install: true

      - name: Get package version
        id: get-package-version
        run: echo "PACKAGE_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;27.0.11902837"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable # Set this to dtolnay/rust-toolchain@nightly
        with:
          targets: aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Build Android APK
        run: pnpm tauri android build
        env:
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/27.0.11902837

      - name: Rename APK file
        run: |
          mv ${{env.APK_FILE_PATH}}/app-universal-release.apk ${{env.APK_FILE_PATH}}/offerWing-${{ steps.get-package-version.outputs.PACKAGE_VERSION }}.apk

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          name: offerWing v${{ steps.get-package-version.outputs.PACKAGE_VERSION }}
          tag_name: v${{ steps.get-package-version.outputs.PACKAGE_VERSION }}
          generate_release_notes: true
          make_latest: true
          files: ${{env.APK_FILE_PATH}}/offerWing-${{ steps.get-package-version.outputs.PACKAGE_VERSION }}.apk
